trigger: none
pr: none

variables:
  # Secret variable containing your private key
  SSH_PRIVATE_KEY: $(SSH_PRIVATE_KEY)   # Add this in pipeline UI as secret

stages:
- stage: Deploy
  displayName: CD - Deploy App
  jobs:
  - deployment: DeployApp
    displayName: Deploy Application
    environment:
      name: 'dev-env'
    pool:
      name: 'pradeep-pool'

    strategy:
      runOnce:
        deploy:
          steps:

          # 1. Download artifact using buildId
          - task: DownloadPipelineArtifact@2
            displayName: 'Download asp-artifact from CI'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: 'task_2_ci'
              runVersion: 'specific'
              runId: '140'
              artifact: 'asp-artifact'
              path: '$(Pipeline.Workspace)/asp-app'

          # 2. Show artifact contents
          - task: CmdLine@2
            displayName: 'Show downloaded artifact'
            inputs:
              script: |
                echo "Downloaded contents:"
                ls -R $(Pipeline.Workspace)/asp-app

          # 3. Setup SSH key from secret
          - task: Bash@3
            displayName: 'Setup SSH key for pipeline'
            inputs:
              targetType: 'inline'
              script: |
                mkdir -p ~/.ssh
                echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
                chmod 600 ~/.ssh/id_ed25519
                ssh-keyscan -H 51.8.104.126 >> ~/.ssh/known_hosts

          # 4. Manual SSH Deployment
          - task: Bash@3
            displayName: 'Deploy App to Linux VM'
            inputs:
              targetType: 'inline'
              script: |
                echo "Starting manual SSH deployment..."

                VM_USER="azureuser"
                VM_HOST="51.8.104.126"
                VM_PATH="/var/www/myapp"

                echo "Copying app files..."
                scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -r $(Pipeline.Workspace)/asp-app/* $VM_USER@$VM_HOST:$VM_PATH/

                echo "Restarting application..."
                ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "sudo systemctl restart myapp.service"

                echo "Deployment completed successfully!"
