trigger: none
pr: none

variables:
  environment: 'dev'
  app_service_name: 'pradeep-app'
  app_resource_group: 'pradeep-rg'
  artifact_name: 'asp-artifact'
  package_path: '$(Pipeline.Workspace)/asp-artifact.zip'

stages:
- stage: Deploy
  displayName: CD - Deploy App
  jobs:
  - deployment: DeployApp
    displayName: Deploy Application
    environment: '$(environment)-app'
    pool:
      name: 'pradeep-pool'
    strategy:
      runOnce:
        deploy:
          steps:

          # 1. Download artifact from CI
          - task: DownloadPipelineArtifact@2
            displayName: 'Download asp-artifact from CI'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: 'task_2_ci'
              runVersion: 'latest'
              artifact: '$(artifact_name)'
              path: '$(Pipeline.Workspace)/asp-artifact'

          - task: Bash@3
            displayName: 'Show downloaded artifact'
            inputs:
              targetType: 'inline'
              script: |
                echo "Downloaded contents:"
                ls -R $(Pipeline.Workspace)/asp-artifact

          # 2. Ensure zip is installed
          - task: Bash@3
            displayName: 'Ensure zip is installed'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                if ! command -v zip >/dev/null 2>&1; then
                  sudo apt-get update
                  sudo apt-get install -y zip
                fi

          # 3. Azure Login via Managed Identity
          - task: Bash@3
            displayName: 'Azure Login (Managed Identity)'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                az login --identity
                az account show

          # 4. Deploy package to App Service using modern command
          - task: Bash@3
            displayName: 'Deploy package to App Service'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                PKG_PATH="$(package_path)"
                if [ ! -f "$PKG_PATH" ]; then
                  echo "Package not found: $PKG_PATH"
                  exit 1
                fi
                echo "Deploying package to App Service: $(app_service_name) in RG: $(app_resource_group)"
                az webapp deploy \
                  --resource-group "$(app_resource_group)" \
                  --name "$(app_service_name)" \
                  --src-path "$PKG_PATH" \
                  --type zip

          # 5. Verify App Service health
          - task: Bash@3
            displayName: 'Verify App Service is up'
            inputs:
              targetType: 'inline'
              script: |
                set -e
                APP_URL="https://$(app_service_name).azurewebsites.net"
                ENDPOINTS=("/" "/api")

                for endpoint in "${ENDPOINTS[@]}"; do
                  echo "Checking ${APP_URL}${endpoint} (up to 5 attempts)"
                  i=0
                  until [ $i -ge 5 ]; do
                    status=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL$endpoint")
                    if [[ "$status" -ge 200 && "$status" -lt 400 ]]; then
                      echo "$endpoint responded with HTTP $status"
                      break
                    fi
                    i=$((i+1))
                    echo "Attempt $i: $endpoint not responding (HTTP $status). Waiting 10s..."
                    sleep 10
                  done
                  if [ "$i" -eq 5 ]; then
                    echo "$endpoint did not respond successfully after retries"
                    exit 1
                  fi
                done

                echo "All endpoints are healthy ✅"
