trigger: none

variables:
  environment: 'dev'
  app_service_name: 'pradeep-app-53426'
  app_resource_group: 'pradeep-2-rg'
  artifact_name: 'asp-artifact'
  package_path: '$(Pipeline.Workspace)/asp-artifact.zip'

jobs:
- deployment: DeployApp
  displayName: 'CD Deployment to App Service'
  environment: "$(environment)-app"
  pool:
    name: pradeep-pool
  strategy:
    runOnce:
      deploy:
        steps:

        - checkout: none

        # ✅ Correct way to fetch CI artifacts
        - task: DownloadPipelineArtifact@2
          displayName: 'Download artifact from CI (task_2_ci)'
          inputs:
            buildType: 'latest'
            project: '$(System.TeamProjectId)'
            definition: 'task_2_ci'        # CI pipeline name
            artifactName: 'asp-artifact'   # CI artifact name
            targetPath: '$(Pipeline.Workspace)/asp-artifact'

        - task: Bash@3
          displayName: 'Ensure zip installed'
          inputs:
            targetType: 'inline'
            script: |
              set -e
              if ! command -v zip >/dev/null 2>&1; then
                sudo apt-get update
                sudo apt-get install -y zip
              fi

        - task: Bash@3
          displayName: 'Create zip package'
          inputs:
            targetType: 'inline'
            script: |
              ART_DIR="$(Pipeline.Workspace)/asp-artifact"
              echo "Artifact folder:"
              ls -la "$ART_DIR"
              cd "$ART_DIR"
              zip -r "$(package_path)" . -x "*/node_modules/*"

        - bash: |
            az login --identity
            az account show
          displayName: "Azure Login"

        - bash: |
            echo "Deploying to App Service..."
            az webapp deployment source config-zip \
              --resource-group "$(app_resource_group)" \
              --name "$(app_service_name)" \
              --src "$(package_path)"
          displayName: "Deploy ZIP to App Service"

        - bash: |
            APP_URL="https://$(app_service_name).azurewebsites.net"
            echo "Checking health: $APP_URL/health"
            curl -I "$APP_URL"
          displayName: "Verify Deployment"
