trigger:
  none

pr:
  none

variables:
  environment: 'dev'
  app_service_name: 'pradeep-app'
  app_resource_group: 'pradeep-rg'
  artifact_name: 'asp-artifact'
  package_path: '$(Pipeline.Workspace)/asp-artifact.zip'

stages:
- stage: Deploy
  displayName: 'CD - Deploy App'
  jobs:
  - deployment: DeployApp
    displayName: 'Deploy Application'
    environment:
      name: '$(environment)-app'
    pool:
      name: 'pradeep-pool'
    strategy:
      runOnce:
        deploy:
          steps:

          # 1. Download artifact from CI
          - task: DownloadPipelineArtifact@2
            displayName: 'Download asp-artifact from CI'
            inputs:
              buildType: 'latest'
              artifact: '$(artifact_name)'
              path: '$(Pipeline.Workspace)/asp-artifact'

          # 2. Show downloaded artifact
          - task: Bash@3
            displayName: 'Show artifact contents'
            inputs:
              targetType: 'inline'
              script: |
                ls -R $(Pipeline.Workspace)/asp-artifact

          # 3. Azure Login (Managed Identity)
          - task: Bash@3
            displayName: 'Azure Login'
            inputs:
              targetType: 'inline'
              script: |
                az login --identity
                az account show

          # 4. Deploy package to App Service
          - task: Bash@3
            displayName: 'Deploy package to App Service'
            inputs:
              targetType: 'inline'
              script: |
                PKG_PATH="$(Pipeline.Workspace)/asp-artifact.zip"
                az webapp deployment source config-zip \
                  --resource-group "$(app_resource_group)" \
                  --name "$(app_service_name)" \
                  --src "$PKG_PATH"

          # 5. Verify App Service endpoints
          - task: Bash@3
            displayName: 'Verify App Service is up'
            inputs:
              targetType: 'inline'
              script: |
                APP_URL="https://$(app_service_name).azurewebsites.net"
                ENDPOINTS=("/" "/api" "/health")
                for endpoint in "${ENDPOINTS[@]}"; do
                  i=0
                  until [ $i -ge 5 ]; do
                    status=$(curl -s -o /dev/null -w "%{http_code}" "$APP_URL$endpoint")
                    if [[ "$status" -ge 200 && "$status" -lt 400 ]]; then
                      echo "$endpoint responded with HTTP $status"
                      break
                    fi
                    i=$((i+1))
                    sleep 10
                  done
                  if [ "$i" -eq 5 ]; then
                    echo "$endpoint failed to respond"
                    exit 1
                  fi
                done
                echo "All endpoints are healthy ✅"
