trigger: none
pr: none

stages:
- stage: Deploy
  displayName: CD - Deploy App
  jobs:
  - deployment: DeployApp
    displayName: Deploy Application
    environment:
      name: 'dev-env'
    pool:
      name: 'pradeep-pool'

    strategy:
      runOnce:
        deploy:
          steps:

          # 1. Download artifact using buildId like your working example
          - task: DownloadPipelineArtifact@2
            displayName: 'Download asp-artifact from CI'
            inputs:
              buildType: 'specific'
              project: '$(System.TeamProjectId)'
              pipeline: 'task_2_ci'         # your CI pipeline
              runVersion: 'specific'
              runId: '140'                  # <-- YOUR BUILD ID
              artifact: 'asp-artifact'
              path: '$(Pipeline.Workspace)/asp-app'

          # 2. Show artifact contents
          - task: CmdLine@2
            displayName: 'Show downloaded artifact'
            inputs:
              script: |
                echo "Downloaded contents:"
                ls -R $(Pipeline.Workspace)/asp-app

          # 3. Manual SSH Deployment (NO service connection)
          - task: CmdLine@2
            displayName: 'Deploy App to Linux VM'
            inputs:
              script: |
                echo "Starting manual SSH deployment..."

                VM_USER="azureuser"
                VM_HOST="51.8.104.126"
                VM_PATH="/var/www/myapp"

                echo "Copying app files..."
                scp -o StrictHostKeyChecking=no -r $(Pipeline.Workspace)/asp-app/* $VM_USER@$VM_HOST:$VM_PATH/

                echo "Restarting application..."
                ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "sudo systemctl restart myapp.service"

                echo "Deployment completed successfully!"
