trigger:
  - master

variables:
  TF_VERSION: '1.6.6'
  environment: 'dev'        # dev or prod
  artifact_name: 'asp-artifact'

pool:
  name: 'pradeep-pool'

steps:

# 1. Checkout repository
- checkout: self

# 2. Setup Node.js
- task: NodeTool@0
  displayName: 'Use Node.js 18.x'
  inputs:
    versionSpec: '18.x'

# 3. Restore dependencies
- task: Bash@3
  displayName: 'Restore npm dependencies'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      cd app
      if [ -f package-lock.json ]; then
        npm ci
      else
        npm install
      fi

# 4. Build the application
- task: Bash@3
  displayName: 'Build application (if applicable)'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      cd app
      if grep -q '"build"' package.json; then
        npm run build
      fi

# 5. Prepare artifact directory
- task: Bash@3
  displayName: 'Package application artifact'
  inputs:
    targetType: 'inline'
    script: |
      set -e
      ART_DIR="$(Build.ArtifactStagingDirectory)/asp-artifact"
      rm -rf "$ART_DIR"
      mkdir -p "$ART_DIR"
      cp -R app/* "$ART_DIR/"
      rm -rf "$ART_DIR/node_modules"
      if [ -f app/package-lock.json ]; then
        cp app/package-lock.json "$ART_DIR/"
      fi

# 6. Zip artifact
- task: Bash@3
  displayName: 'Create ZIP of artifact'
  inputs:
    targetType: 'inline'
    script: |
      ART_DIR="$(Build.ArtifactStagingDirectory)/asp-artifact"
      ZIP_PATH="$(Build.ArtifactStagingDirectory)/asp-artifact.zip"
      cd "$ART_DIR"
      zip -r "$ZIP_PATH" . -x "node_modules/*"
      echo "ZIP created at $ZIP_PATH"

# 7. Publish artifact
- task: PublishBuildArtifacts@1
  displayName: 'Publish application artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/asp-artifact'
    ArtifactName: 'asp-artifact'
    publishLocation: 'Container'
